import React from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import './index.css';
import {FaTrash, FaPencilAlt} from 'react-icons/fa'


function Table() {
  const data = [
    {
        Id:1,
        Book_Type:'kinyarwanda',
        Book_Level:'S1',
        Book_Number:'007',
        Student_Name:'Kalisa',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:2,
        Book_Type:'Mathematics',
        Book_Level:'S1',
        Book_Number:'002/2023',
        Student_Name:'Magayane',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:3,
        Book_Type:'History',
        Book_Level:'S1',
        Book_Number:'001/2024',
        Student_Name:'Kalisa',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:4,
        Book_Type:'Geograph',
        Book_Level:'S1',
        Book_Number:'00003',
        Student_Name:'Barnabe',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:5,
        Book_Type:'French',
        Book_Level:'S1',
        Book_Number:'0002',
        Student_Name:'Abel',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:6,
        Book_Type:'kiswahili',
        Book_Level:'S1',
        Book_Number:'0001',
        Student_Name:'Brigitte',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:7,
        Book_Type:'kinyarwanda',
        Book_Level:'S1',
        Book_Number:'007',
        Student_Name:'Kalisa',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:8,
        Book_Type:'Mathematics',
        Book_Level:'S1',
        Book_Number:'002/2023',
        Student_Name:'Magayane',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:9,
        Book_Type:'History',
        Book_Level:'S1',
        Book_Number:'001/2024',
        Student_Name:'Kalisa',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:10,
        Book_Type:'Geograph',
        Book_Level:'S1',
        Book_Number:'00003',
        Student_Name:'Barnabe',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:11,
        Book_Type:'French',
        Book_Level:'S1',
        Book_Number:'0002',
        Student_Name:'Abel',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:12,
        Book_Type:'kiswahili',
        Book_Level:'S1',
        Book_Number:'0001',
        Student_Name:'Brigitte',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:13,
        Book_Type:'kiswahili',
        Book_Level:'S1',
        Book_Number:'0001',
        Student_Name:'Kabalisa',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:14,
        Book_Type:'kiswahili',
        Book_Level:'S1',
        Book_Number:'0001',
        Student_Name:'Kabarebe',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:15,
        Book_Type:'kiswahili',
        Book_Level:'S1',
        Book_Number:'0001',
        Student_Name:'Kabashengure',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:16,
        Book_Type:'kinyarwanda',
        Book_Level:'S1',
        Book_Number:'007',
        Student_Name:'Kalisa',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:17,
        Book_Type:'Mathematics',
        Book_Level:'S1',
        Book_Number:'002/2023',
        Student_Name:'Magayane',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:18,
        Book_Type:'History',
        Book_Level:'S1',
        Book_Number:'001/2024',
        Student_Name:'Kalisa',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:19,
        Book_Type:'Geograph',
        Book_Level:'S1',
        Book_Number:'00003',
        Student_Name:'Barnabe',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:20,
        Book_Type:'French',
        Book_Level:'S1',
        Book_Number:'0002',
        Student_Name:'Abel',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:21,
        Book_Type:'kiswahili',
        Book_Level:'S1',
        Book_Number:'0001',
        Student_Name:'Brigitte',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:22,
        Book_Type:'kiswahili',
        Book_Level:'S1',
        Book_Number:'0001',
        Student_Name:'Kabalisa',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:23,
        Book_Type:'kiswahili',
        Book_Level:'S1',
        Book_Number:'0001',
        Student_Name:'Kabarebe',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:24,
        Book_Type:'kiswahili',
        Book_Level:'S1',
        Book_Number:'0001',
        Student_Name:'Kabashengure',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:25,
        Book_Type:'kinyarwanda',
        Book_Level:'S1',
        Book_Number:'007',
        Student_Name:'Kalisa',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:26,
        Book_Type:'kinyarwanda',
        Book_Level:'S1',
        Book_Number:'007',
        Student_Name:'ITANGIRI',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:27,
        Book_Type:'Francais',
        Book_Level:'S1',
        Book_Number:'007',
        Student_Name:'MUNGANYIMANA',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:28,
        Book_Type:'kinyarwanda',
        Book_Level:'S1',
        Book_Number:'007',
        Student_Name:'MUKAKADAGE',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:29,
        Book_Type:'Kiswahili',
        Book_Level:'S1',
        Book_Number:'007',
        Student_Name:'MUKAGASISI',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:30,
        Book_Type:'kinyarwanda',
        Book_Level:'S1',
        Book_Number:'007',
        Student_Name:'Kalisa',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:31,
        Book_Type:'kinyarwanda',
        Book_Level:'S1',
        Book_Number:'007',
        Student_Name:'Kalisa',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:32,
        Book_Type:'kinyarwanda',
        Book_Level:'S1',
        Book_Number:'007',
        Student_Name:'Kalisa',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
    {
        Id:33,
        Book_Type:'kinyarwanda',
        Book_Level:'S1',
        Book_Number:'007',
        Student_Name:'Kalisa',
        Student_Class:'S1A',
        Borrowing_Date:'1/2/2024'
    },
];

  return (
    <div className="container mt-5">
     
      <table className="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Book Type</th>
            <th>Book Number</th>
            <th>Book Level</th>
            <th>Stud Name</th>
            <th>Class</th>
            <th>Date</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {data.map((item) => (
            <tr key={item.Id}>
              <td>{item.Book_Type}</td>
              <td>{item.Book_Number}</td>
              <td>{item.Book_Level}</td>
              <td>{item.Student_Name}</td>
              <td>{item.Student_Class}</td>
              <td>{item.Borrowing_Date}</td>
              <td>
                   <span className='books_actions'>
                        <FaTrash className='delete-btn' />
                        <FaPencilAlt className='edit-btn' />
                    </span>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default Table;
